### ISSUE TITLE
Not working on k210

### ISSUE THREAD

**Issue by pritamghanghas** [PureHing/face-mask-detection-tf2#13]
Hi

I have tried both nncase0.2 and 0.1 with no luck with MaixPy. 

Here are the outputs 
when trying to convert with nncase 0.1 it gives relu not supported. I changed that to leakyrelu because their documentation says leakyrelu is supported. But then I get an exception in nncase:
``` 
   Fatal: Nullable object must have a value.
   System.InvalidOperationException: Nullable object must have a value.
   at System.Nullable`1.get_Value()
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertReshape(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 197
   at NnCase.Converter.Converters.TfLiteToGraphConverter.ConvertOperator(Operator op) in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 97
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToList()
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NnCase.Converter.Converters.TfLiteToGraphConverter.Convert() in D:\Work\Repository\nncase\src\NnCase.Converter\Converters\TfLiteToGraphConverter.cs:line 34
   at NnCase.Cli.Program.Main(String[] args) in D:\Work\Repository\nncase\src\NnCase.Cli\Program.cs:line 113
   at NnCase.Cli.Program.<Main>(String[] args) 
```

With nncase 0.2 the model converts but it doesn't load under maixpy, give following error:
```
ValueError: [MAIXPY]kpu: load error -3
```
basically kpu.load() lead to this error. From the documentation I couldn't find what -3 means. 

I tried reducing layers in case it is  a size issue, but still the issue persists. 

Next I will try without maixpy, using their SDK, that will take some time.

I am sure the problem is with nncase and k210 not with this code or model. Opened a ticket on their maixpy repo as well, lets see what they say about it.

**Comment by pritamghanghas** [comment]
the model loaded on an older version of maixpy, but gets stuck on first inference itself.

**Comment by pritamghanghas** [comment]
using nncase 0.2beta2 the generated model doens't get stuck as well. Now only thing remaining is to write code for inference, because tf and np classes are not there on k210, and there is lot of transformations before bounding box can be extracted.

**Comment by PureHing** [comment]
@pritamghanghas As far as I know maixpy's inference api is for yolov2,You'd better develop on the official SDK, refer to the [example](https://github.com/kendryte/nncase/tree/master/examples).
